### ISSUE TITLE
documentation on how to "paginate" results

### ISSUE THREAD

**Issue by twelve17** [glebm/order_query#13]
I have put "paginate" in quotes because I am not referring to the paginate found in a offset/query based "page x of y" scheme, but as a "page" or chunk of rows in a infinite scrolling scheme.

The best I can tell from studying this library and the postings in the "use the index" site, the cursors are identified by the primary key of the row, and that I would still need to use `limit` in combination with those PKs to chunk the results.

With this in mind, I am not sure how to go about this properly with the Point/Space APIs in this library given a dynamic query.

- On the first keyset paginated request for some records, the client would need to be given the following bits of info in the response:
  - The records in the current "page"
  - The cursor to get the previous "page"
  - The cursor to get the next "page"

  In order to get the first item above, I could do a `seek` per the docs:
  ```
    Post.visible.seek([:id, :desc]) 
  ```
  I could add a `limit` to change the behavior of the resulting `after` to infer the cursor for the next "page":
  ```
    Post.limit(10).visible.seek([:id, :desc]) 
  ```
  However, I actually would have to fetch `limit +1` for the`space.last` to point to the cursor for the next "page".

  I am already feeling like I am misunderstanding something. :) 

- On subsequent requests (e.g. now I have a cursor-- say id 42), I could use:
  ```
     Post.find(42).seek([:id, :desc])
  ```
   Now I have a `Point` with a `before` and `after`. The before I won't use since this is an infinite scroller and the data is already on the client (otherwise I'd have to do additional calculation to get the before "page"'s start position).  The `after` once again would include all records, not just the next chunk, so calculating the cursor for the next "page" would involve similar `limit +1` logic from above. 

Now I definitely feel like I'm not using this library correctly!

If you could be so kind to provide some assistance, I would be willing to write some documentation on the wiki.

**Comment by saturnflyer** [comment]
Not documentation but I went looking for examples where others are using it.

This project uses order_query.
https://github.com/MidnightRiders/MemberPortal/blob/03f72f47a650eb609d9b1c8e595ae3ad546ab581/app/views/matches/show.html.haml

In case that project disappears, this is the view that renders the next/previous links:

```
.row
  .small-4.medium-3.large-2.columns
    - if @order_point.previous(false)
      = link_to @order_point.previous(false), class: "button small expand primary-bg #{@order_point.previous(false).home_team.abbrv.downcase}" do
        = icon 'arrow-left'
        = @order_point.previous(false).home_team.abbrv
        v
        = @order_point.previous(false).away_team.abbrv
        = @order_point.previous(false).kickoff.strftime('%_m.%-d')
  .small-4.medium-6.large-8.columns.text-center
    = link_to matches_path(date: @match.kickoff.to_date), class: 'button small' do
      = icon 'calendar fa-fw'
      Back
  .small-4.medium-3.large-2.columns.right
    - if @order_point.next(false)
      = link_to @order_point.next(false), class: "button small expand primary-bg #{@order_point.next(false).home_team.abbrv.downcase}" do
        = @order_point.next(false).home_team.abbrv
        v
        = @order_point.next(false).away_team.abbrv
        = @order_point.next(false).kickoff.strftime('%_m.%-d')
        = icon 'arrow-right'
```

The controller sets up the `@order_point` object by doing `@order_point = @match.order_selected(Match.all_seasons)`

And the Match model has this code:

```
  order_query :order_selected,
              %i(kickoff asc),
              %i(location asc)
```

I **have not** pulled that project and attempted to run it. I've only sorted through to see how order_query was being used.

**Comment by niborg** [comment]
Hi, any additional documentation underway? If not, I'd be willing to contribute. My sense is that the usage explanation for the 'order_query' method could be a little clearer, and the examples might to well to use the limit method to make clear how the gem expects you to us AR to receive chunks.

**Comment by glebm** [comment]
Sorry about not being very clear in the readme, I'm not sure how to improve it. Nothing is underway currently. Please go ahead and send a PR.

**Comment by niborg** [comment]
@glebm Took a shot at clarifying the documentation on points where I got a little confused. And added a point about using limit. Let me know what you think!

**Comment by twelve17** [comment]
Hi everyone, thanks for the various explanations, and thanks @niborg for the PR to expand the documentation. I'm getting a clearer idea of how this library can be used.
