### ISSUE TITLE
is sorting by an associated column supported?

### ISSUE THREAD

**Issue by twelve17** [glebm/order_query#18]
Given this AR model set:

```
class Sandwich < ActiveRecord::Base
  has_many toppings
  include OrderQuery
end

# has a name attribute
class Toppings < ActiveRecord::Base
end
```

Could you order by the associated column, `Topping.name`?

I have not had luck with this.  It appears that the order clause prepends the base model's table name, unless [you pass a `sql` option](https://github.com/glebm/order_query#usage) with the raw value:

```
# fails, tries to do "sandwich.toppings.name"
point = Sandwich.include(:toppings).joins(:toppings).seek(*[[:"toppings.name", :desc]])

# works, I suppose the first arg is ignored since the has is passed in as a 3rd arg
point = Sandwich.include(:toppings).joins(:toppings).seek(*[[:"toppings.name", :desc, {:sql=>'toppings.name'} ]])
```

However, calling `point.after` above throws an error:
```
undefined method `toppings.name' for #<Sandwich:00x00...>
```

**Comment by glebm** [comment]
What do you want to achieve? It's a has_many association, so which one of the many do you want it to sort by? Max? Lexicographic?

**Comment by twelve17** [comment]
Apologies, I probably should have used a `has_one` in the example.  Thus it would be a one-to-one join of two tables, sorting by a field in the second table.

**Comment by glebm** [comment]
For the `has_one` case this should be sufficient:

```ruby
point = Sandwich.joins(:topping).seek([:topping_name, :desc, sql: 'toppings.name'])

class Sandwich < ...
  def topping_name
    topping.name
  end
end
````

**Comment by twelve17** [comment]
@glebm does calling `after` on that `point` work for you?

**Comment by glebm** [comment]
The result of that is not really a point but a `Space`. You need to call `at` to get a Point.

**Comment by twelve17** [comment]
Apologies for the delay. Indeed, once I get a `Point`, calling `after` on it is where I get the error.  I've created a [rails spec gist](https://gist.github.com/twelve17/e318aa8953ae3bc79e65b37218389e07) to replicate the error.

The spec creates models `Company` and `Employee`, the latter is a `has_one` association of the former.  The spec is designed to connect to a mysql database via these environment variables:

- `DB_HOST`
- `DB_USERNAME`
- `DB_PASSWORD`
- `DB_NAME`
- optional: `DB_PORT` (defaults to 3306)

The test will create the database, create the table structure, then seed the data with a few records: two `Employee` records, each with a `Contract` associated with it.

This is the result of the test I'm encountering:

```

  1) OrderQuery search sort on secondary join table can fetch 'next' on a Employee point when sorting by contract.contract_type
     Failure/Error: record = space.at(Employee.first).after(false).limit(1)
     
     NoMethodError:
       undefined method `contract_type' for #<Employee id: 1, name: "John", email: "john@foo.com">
       Did you mean?  contract
     # ./spec/association_spec.rb:145:in `block (4 levels) in <top (required)>'

Finished in 2.91 seconds (files took 0.89039 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/association_spec.rb:141 # OrderQuery search sort on secondary join table can fetch 'next' on a Employee point when sorting by contract.contract_type
```

I feel like I must be doing something wrong.  Help is appreciated!

**Comment by glebm** [comment]
Closing as it's old. In case you still need help, consider StackOverflow.

**Comment by twelve17** [comment]
@glebm were you not able to replicate the problem with the gist I created?

**Comment by glebm** [comment]
I've had a look at your gist works if you simply:

1. Pass the correct arguments to order_query

   ```diff
   -space = Employee.joins(:contract).seek([:contract_type, :desc, "contract.contract_type"])
   +space = Employee.joins(:contract).seek([:contract_type, :desc, sql: "contract.contract_type"])
   ```

2. Define the `contract_type` method on `Employee`:

   ```diff
   delegate :contract_type, to: :contract
   ```

**Comment by twelve17** [comment]
Hi @glebm , I apologize for not responding to this sooner. I re-reviewed this today and now understand your approach, have been able to reproduce it locally.  Thanks again for your help!
