### ISSUE TITLE
Calling prev and next when the ordering model attribute is enumerable creates an invalid SQL where clause

### ISSUE THREAD

**Issue by gfowley** [glebm/order_query#31]
The model:
``` ruby
class Address < ApplicationRecord
  include OrderQuery
  belongs_to :network
  validates :inet, presence: true
  order_query :by_inet, [ :inet ]

  def next loop_around: false
    self.by_inet.next(loop_around)
  end

  def prev loop_around: false
    self.by_inet.previous(loop_around)
  end

end
```
The model field named ```inet``` is an [IPAddress](https://github.com/ipaddress-gem/ipaddress).
IPAddress includes Enumerable (a network IP address could be said to cover multiple IP addresses).

Calling ```@address.prev``` from a view fails with:
```
  Rendering addresses/show.html.erb
  Address Load (0.9ms)  SELECT "addresses".* FROM "addresses" WHERE ("addresses"."inet" <= inet '10.7.7.4/30',inet '10.7.7.5/30',inet '10.7.7.6/30',inet '10.7.7.7/30' AND ("addresses"."inet" < inet '10.7.7.4/30',inet '10.7.7.5/30',inet '10.7.7.6/30',inet '10.7.7.7/30' OR "addresses"."inet" = inet '10.7.7.4/30',inet '10.7.7.5/30',inet '10.7.7.6/30',inet '10.7.7.7/30' AND "addresses"."id" < 20)) ORDER BY "addresses"."inet" DESC, "addresses"."id" DESC LIMIT $1  [["LIMIT", 1]]
  ↳ app/models/address.rb:47:in `prev'
  Rendered addresses/show.html.erb (Duration: 2.6ms | Allocations: 2915)
Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.1ms | Allocations: 3562)
  
ActionView::Template::Error (PG::DatatypeMismatch: ERROR:  argument of AND must be type boolean, not type inet
LINE 1: ....4/30',inet '10.7.7.5/30',inet '10.7.7.6/30',inet '10.7.7.7/...
                                                             ^
```
The expected SQL where clause should not contain the 4 enumerated IP addresses covered by ```'10.7.7.7/30'```. It should contain only a single ```inet '10.7.7.7/30'```, something like:
```
... WHERE ("addresses"."inet" <= inet '10.7.7.7/30' ... )
```
I suspect this would happen for any model attributes that include Enumerable, probably as a result of splatting the attribute when building the where clause ?

FYI: The ```inet '10.7.7.7/30'``` is created by a custom PostgreSQL adapter as required to handle PG ```inet``` data types. It works as expected.
 
FYI: ```Address.by_inet``` works as expected:
```
  Rendering addresses/index.html.erb within layouts/application
  Address Load (0.4ms)  SELECT "addresses".* FROM "addresses" ORDER BY "addresses"."inet" ASC, "addresses"."id" ASC
  ↳ app/views/addresses/_table.html.erb:29
```
BTW: Thanks for creating this gem, it solves an unexpectedly difficult problem very well.

**Comment by gfowley** [comment]
I finally tracked down the actual cause of the issue, sorry for the false alarm.
 
When quoting bound attribute values ActiveRecord enumerates objects that respond to map:
```ruby
def quote_bound_value(value, c = connection)
  if value.respond_to?(:map) && !value.acts_like?(:string)
    values = value.map { |v| v.respond_to?(:id_for_database) ? v.id_for_database : v }
    if values.empty?
      c.quote(nil)
    else
      values.map! { |v| c.quote(v) }.join(",")
    end
  else
    value = value.id_for_database if value.respond_to?(:id_for_database)
    c.quote(value)
  end
end

```
Patching ```IPAddress``` with ```#acts_like?``` prevents the enumeration and builds a correct SQL where clause.
 
Thanks for listening (I really must buy a rubber duck :-).

**Comment by glebm** [comment]
Glad you've figured it out!
