### ISSUE TITLE
#seek or #at with previously specified order

### ISSUE THREAD

**Issue by gwcoffey** [glebm/order_query#5]
If I do this:

    relation = MyModel.order_foo

My relation is ordered according to the `order_foo` specified in the model. If I then want to get a `Point` I have to do this:

    point = relation.order_foo_at(instance)

So I've now specified the ordering twice. If I change the ordering I have to change it in both places. If I make the ordering selection complicated based on some logic (parameterized, etc...) I have to have that logic in two places, or use `relation.send`, or use seek, etc...

Is there a way to avoid this repetitiveness? Since the relation has already been ordered using order_query, it feels like I should be able to do this:

    point = relation.at(instance)

or:

    point = instance.seek(relation)

or something similar?

Is there a way to get a point based on the previously used ordering without re-specifying it?

**Comment by glebm** [comment]
The relation is used for filtering only and not for ordering. It does not need to be ordered, and its order is ignored.

```
MyModel.order_foo_at(instance)
```


The default relation for `instance.order_foo` is MyModel:

```
instance.order_foo #=> Point
instance.order_foo_reverse #=> Point
MyModel.find(123).order_foo(MyModel.my_scope) #=> Point
```

**Comment by gwcoffey** [comment]
In my case I'm trying to coordinate this across actions. I have a notion of the "current" selection and ordering (session based). The user may view an `index` page, in which case we show the selected records (where) in the right order (order_{whatever}). They may also view a `show` page with details for one object, as well as next/previous links and a list. The detail page uses the same selection and ordering previously used. 

I'm trying to avoid this:

    def index
       @posts = posts_relation
    end

    def show
       @post = Post.find(params[:id])
       @posts = posts_relation
       @point = @posts.order_home_at(@post)
       # ^^^--- I don't like referring to order_home here
    end

    private

    def posts_relation
        Post.where(...).order_home
    end

Theoretically the relation already knows it has the `order_home` ordering applied. I think the right answer is to re-architect things so I use spaces instead of relations..

    def index
       @posts = posts_space.relation
    end

    def show
       @post = Post.find(params[:id])
       @posts = posts_space.relation
       @point = posts_space.at(@post)
    end

    private

    def posts_space
       Post.where(...).seek(...order specification...)
    end

Is that the right idea? In my case I don't necessarily want an ad hoc ordering (which is what `Space` is documented for) but I do want the concept of a space. I'd rather have the order specification(s) in the `Post` model. I could of course do this:

    class Post < ActiveRecord::Base
       ORDER_HOME = [[:description]]
    end

and in `PostsController#post_space`:

    def post_space
       Post.where(...).seek(Post::ORDER_HOME)
    end

I'm just trying to understand the best approach. Thanks for your help and a nice looking gem! Sorry to be thick.

Geoff

**Comment by glebm** [comment]
The `.order_home_space` method returns a Space. This method is not documented, but it should be:

```ruby
Post.where(...).order_home_space
```

**Comment by gwcoffey** [comment]
Ahh perfect. Thank you! Will this method be maintained moving forward?

**Comment by glebm** [comment]
Yes, this is public API and will be maintained. I will add this method to the Readme. Good catch, thanks!
