### ISSUE TITLE
Can this sort on nested attributes?

### ISSUE THREAD

**Issue by MasterSlowPoke** [glebm/order_query#6]
I've got some data that I'd like to get the next and previous results from based off a nested attribute. Something like ordering posts by last comment date on that post.

**Comment by glebm** [comment]
Yes, but you'd need to do a join / subquery first, then just pass the `sql: ` option for the order spec.

```
class Post
  order_query :order_by_last_comment_at,
    [:last_comment_at, :desc, sql: 'comments.created_at']

  def last_comment_at
    ...
  end
end
```

**Comment by MasterSlowPoke** [comment]
Gotcha, thanks, that works great. The next field I want to order by looks like this:

```ruby
  def title
    return company_name if company_name.present?
    return website if website.present?
    "New Lead"
  end
```
I'm not sure how to translate that into a SQL expression, or if it's even possible. I tried
```ruby
  order_query :order_title, [:title, :desc, sql: "(company_name != NULL ? company_name : (website != NULL ? website : 'New Lead'))"]
```
but in addition to being a terrible nested ternary operation, it didn't work.

**Comment by glebm** [comment]
SQL doesn't have ternary expressions, and `NULL` comparison must be done with IS (NOT) NULL, but it has the `[COALESCE](http://dev.mysql.com/doc/refman/5.0/en/comparison-operators.html#function_coalesce)` function that returns the first non-null argument:

```sql
COALESCE(company_name, website, "New Lead")
```

Note that this doesn't test for empty string, and if company_name or website can be empty strings, this can be done instead:

```sql
COALESCE(NULLIF(company_name, ""), NULLIF(website, ""), "New Lead")
```
