### ISSUE TITLE
.previous always showing first record when limiting scope

### ISSUE THREAD

**Issue by maskott** [glebm/order_query#8]
First of all, I am a total noob, so sorry if I have this set up incorrectly or if this is not the proper channel to communicate this type of issue. I still have so much to learn!

I have your order_query gem working beautifully for my Bottle class as such:
```ruby
class Bottle < ActiveRecord::Base
  ....
  include OrderQuery
  order_query :order_home,
    [:name],
    [:id]
end
```
When I use it in my controller like `@b = Bottle.order_home_at(@bottle)`, everything works as expected. I can use `@b.next.id` and `@b.previous.id` to do what I'm trying to accomplish. 

However, when I try to limit the scope of the query to match my UI, with something like this `@b = Bottle.order(:name, :id).includes(:liquor_type).where("liquor_types.name" => params[:type]).order_home_at(@bottle)` I run into what may be a bug.

I seem to be able to use `@b.next.id` with expected behavior, but `@b.previous.id` always returns the `id` of the _first_ record in the intended set.

Am I doing something wrong (probably), or have I discovered a bug? Thank you for your help and for making such a cool gem!

**Comment by glebm** [comment]
Order query uses ActiveRecord's `#order` method (not `#reorder`) to add the `ORDER BY` clause. It probably should use `reorder`. Meanwhile, try removing the `.order()` from your scope, i.e.:

```ruby
Bottle.includes(:liquor_type).where(liquor_types: {name: params[:type]}).
    order_home_at(@bottle)
```

**Comment by maskott** [comment]
Thanks @glebm for the fast response! That seemed to fix the issue immediately.
