### ISSUE TITLE
Not compatible with rails 5 

### ISSUE THREAD

**Issue by bigcurl** [glebm/order_query#9]
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:

        order_query was resolved to 0.3.2, which depends on
          activerecord (~> 4.0)

    rails (= 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
      activerecord (= 5.0.0.beta1)

**Comment by glebm** [comment]
Pushed v0.3.3 to address this.
